config/routes.rb
Rails.application.routes.draw do
  get 'favorites/index'

  get 'sessions/new'

  post "/" => "pages#index"
  root 'pages#index'

  post 'rakuten_search' => 'rakuten#search'
  get 'rakuten_search' => 'rakuten#search'
  get "/tweets/search" => 'tweets#search'


  get 'auth/:provider/callback' => 'users#create'#このpathを通して認証が行われる。
  root 'home#top'

  post '/favorites', to: 'favorites#create'
  get '/favorites', to: 'favorites#index'
  delete '/favorites', to: 'favorites#delete'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources 'users'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :favorites
end

app/models/tweet.rb
class Tweet
  # プロパティの設定
  attr_accessor :contents

  def initialize(contents)
    @contents = contents
  end
end

app/models/user.rb
class User < ApplicationRecord
  def self.find_or_create_from_auth_hash(auth_hash)
   provider = auth_hash[:provider]#providerはどのサービスで認証したのかを見分けるもの
   uid = auth_hash[:uid]
   name = auth_hash[:info][:name]
   image_url = auth_hash[:info][:image]

   #find_or_create_by()は()の中の条件のものが見つければ取得し、なければ新しく作成するというメソッド
   self.find_or_create_by(provider: provider,uid: uid) do |user|
     user.username = name
     user.image_url = image_url
   end
  end

  has_many :favorites
  has_many :items, through: :favorites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @item ||= Item.find_by(rakutenitem_id: params[:rakutenitem_id])
    if @item.nil?
      @item = Item.new
      @item.rakutenitem_id = params[:rakutenitem_id]
      @item.item_name = params[:item_name]
      @item.item_url = params[:item_url]
      @item.itemimage_url = params[:itemimage_url]
      @item.save
    end
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.item_id = @item.id
    if favorite.save
      redirect_to rakuten_search_path(keyword: params[:keyword]), notice: 'お気に入りに登録しました'
    else
      redirect_to rakuten_search_path(keyword: params[:keyword]), notice: 'お気に入り登録に失敗しました'
    end
  end

  def delete
    @item ||= Item.find_by(rakutenitem_id: params[:rakutenitem_id])
    favorite = Favorite.find_by(user_id: current_user.id, item_id: @item.id)
    if favorite.destroy
      redirect_to rakuten_search_path(keyword: params[:keyword]), notice: 'お気に入りを解除しました'
    else
      redirect_to rakuten_search_path(keyword: params[:keyword]), notice: 'お気に入り解除に失敗しました'
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    client = Twitter::REST::Client.new do |config|
      # 事前準備で取得したキーのセット
      config.consumer_key         = "9ANwqVTcD0vBHxhifWw3liUGB"
      config.consumer_secret      = "pSfA7G3bAQlMBHoX0jZsY52KYaN095pajo33y50BhksMKwIjoJ"
    end
    @trends = client.trends(1118370)
    @trends.each do |trend|
      t = trend.name.dup
      puts t.gsub!(/(#)/, '')
      #puts t
    end
    @trends.each do |trend|
      t = trend.name
      puts t.delete("#")
    end

    @tweets = []
    since_id = nil

    # 検索ワードが存在していたらツイートを取得
    if params[:keyword].present?
      # リツイートを除く、検索ワードにひっかかった最新30件のツイートを取得する
      tweets = client.search(params[:keyword], count: 30, result_type: "recent", exclude: "retweets", since_id: since_id)
      # 取得したツイートをモデルに渡す
      tweets.take(30).each do |tw|
        tweet = Tweet.new(tw.full_text)
        @tweets << tweet
      end
    end
      @trends = client.trends(1118370)#japan
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweets } # jsonを指定した場合、jsonフォーマットで返す
      format.json { render json: @trends } # jsonを指定した場合、jsonフォーマットで返す
    end
  end
end

app/controllers/rakuten_controller.rb
class RakutenController < ApplicationController
  def search
    @keyword = params[:keyword]

    if params[:keyword]  != ""
      @items = RakutenWebService::Ichiba::Item.search(keyword: params[:keyword].delete("#"), affiliateId: "16a1078a.5776ab5e.16a1078b.4f3c0e15", orFlag: 1)

      client = Twitter::REST::Client.new do |config|
        # 事前準備で取得したキーのセット
        config.consumer_key         = "9ANwqVTcD0vBHxhifWw3liUGB"
        config.consumer_secret      = "pSfA7G3bAQlMBHoX0jZsY52KYaN095pajo33y50BhksMKwIjoJ"
      end

      @tweets = []

      since_id = nil
      # 検索ワードが存在していたらツイートを取得
      if params[:keyword].present?
        # リツイートを除く、検索ワードにひっかかった最新30件のツイートを取得する
        tweets = client.search(params[:keyword], count: 30, result_type: "recent", exclude: "retweets", since_id: since_id)
        # 取得したツイートをモデルに渡す

        # tweetを画像付きで表示
        @t_image = []
          i = 0
          tweets.take(30).each do |tw|
            tweet = Tweet.new(tw.full_text)
            @tweets << tweet
            @t_image_i = nil
            tw.media.each do |t|
              @t_image_i = t.media_url
            end
            @t_image[i] =  @t_image_i
            i += 1
          end
      end
      #トレンド取得エリア指定
        @trends = client.trends(1118370)#japan
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @tweets } # jsonを指定した場合、jsonフォーマットで返す
        format.json { render json: @trends } # jsonを指定した場合、jsonフォーマットで返す
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def destroy
    log_out
    redirect_to root_url
  end

private
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def search
      client = Twitter::REST::Client.new do |config|
        # 事前準備で取得したキーのセット
        config.consumer_key         = "9ANwqVTcD0vBHxhifWw3liUGB"
        config.consumer_secret      = "pSfA7G3bAQlMBHoX0jZsY52KYaN095pajo33y50BhksMKwIjoJ"
      end

      @trends = client.trends(1118370)
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @trends } # jsonを指定した場合、jsonフォーマットで返す
      end
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    user = User.find_or_create_from_auth_hash(request.env['omniauth.auth'])
    #request.env['omniauth.auth']はTwitter認証で得た情報を格納するもの
    if user
    session[:user_id] = user.id
    redirect_to root_path, notice: "ログインしました。"
    else
    redirect_to root_path, notice: "失敗しました。"
    end
  end
  private
  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def favorited? item_id
    !current_user.items.find_by(rakutenitem_id: item_id).nil?
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/favorites/index.html.erb
<% @favorites.each do |f| %>
<tr>
 <td><%= image_tag favorite.itemimage_url %></td>
 <td><%= link_to favorite.item_name, "#{favorite.item_url}" %></td>
 <td></td>
</tr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mur</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    
  </body>
</html>

app/views/pages/index.html.erb
<div id="container">
  <div id="header" class="header_logo">
    <ul>
      <li id="logo">
      <%= link_to root_path do %>
      <%= image_tag 'icons/urge_logo.png', class: 'urge_logo' %></li>
      <% end %>
      <% if logged_in? %>
        <!--
        <li align="center"><%= link_to 'お気に入り一覧', root_path %></li>
        -->
        <br>
        <li align="center"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
      <% else %>
      <br>
        <li align="center"><%= link_to 'Twitterアカウントでログイン', '/auth/twitter' %></li>
      <% end %>
    </ul>
  </div>
  <div id="wrapper">
    <div id="boxA">
      <br>
      <%= form_tag :rakuten_search, method: :get do  %>
        <%= label_tag :keyword, '' %>
        <%= text_field_tag 'keyword', params[:keyword] %>
        <%= submit_tag "検索" %>
      <% end %>
      <% if @trends.present? %>
        <ul>
          <% @trends.each_with_index do |trend, i| %>
            <div class="list">
              <li> <%= link_to trend.name, rakuten_search_path(keyword: trend.name) %> </li>
            </div>
          <% end %>
        </ul>
      <% end %>
    </div>
    <div id="boxB">
      <% if @tweets.present? %>
        <b>検索結果</b>
        <ul>
          <% @tweets.each_with_index do |tweet, i| %>
            <div class="list">
              <li>Tweet<%= i %>: <%= tweet.contents %> </li>
            </div>
          <% end %>
        </ul>
      <% else %>
        <h2>検索結果がありません</h2>
      <% end %>
    </div>
    <div id="boxC">
      <% if @items.present? %>
        <table>
          <tbody>
            <thead>
              <tr id=price>
              <th><nobr>商品画像</nobr></th>
              <th id=texit_white>商品名</th>
              <th>価格</th>
              </tr>
            </thead>
            <% @items.each do |item| %>
              <tr>
                <td><%= image_tag item["smallImageUrls"][0] %></td>
                <td><%= link_to truncate(item.name, length: 50 ), "#{item.url}" %></td>
                <td id=texit_white align="right"><%= number_with_delimiter(item.price) %>円</td>
                <td><%= image_tag 'icons/heart.png', class: 'topic-index-icon' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <h2 id=texit_white>検索結果がありません</h2>
      <% end %>
    </div>
  </div>
  <div id="footer">
    <br>
    <br>
    <p id=texit_white align="center">Copyright © <%= Date.today.year %> Urge Inc. All rights reserved.</p>
  </div>
</div>

app/views/rakuten/search.html.erb
<div id="container">
  <div id="header" class="header_logo">
    <ul>
      <li id="logo">
      <%= link_to root_path do %>
      <%= image_tag 'icons/urge_logo.png', class: 'urge_logo' %></li>
      <% end %>
      <% if logged_in? %>
        <!--
        <li align="center"><%= link_to 'お気に入り一覧', root_path %></li>
        -->
        <br>
        <li align="center"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
      <% else %>
      <br>
      <!--Twitterアカウントでログイン-->
        <li align="center"><%= link_to 'Twitterアカウントでログイン', '/auth/twitter' %></li>
      <% end %>
    </ul>
  </div>
  <div id="wrapper">
    <div id="boxA">
      <br>
      <%= form_tag :rakuten_search, method: :get do %>
        <%= label_tag :keyword, '' %>
        <%= text_field_tag 'keyword', params[:keyword] %>
        <%= submit_tag "検索" %>
      <% end %>
      <% if @trends.present? %>
        <ul>
          <% @trends.each_with_index do |trend, i| %>
            <div class="list">
              <li> <%= link_to trend.name, rakuten_search_path(keyword: trend.name) %> </li>
            </div>
          <% end %>
        </ul>
      <% end %>
    </div>
    <div id="boxB">
      <% if @tweets.present? %>
        <b>検索結果</b>
        <ul>
          <% @tweets.each_with_index do |tweet, i| %>
          <div class="search-list">
             <li><%= tweet.contents %></li>
             <li><%= image_tag @t_image[i], style: 'height:auto%;width:100%;' if !@t_image[i].nil? %></li>
           </div>
          <% end %>
        </ul>
      <% else %>
        <h2 class="texit_white">検索結果がありません</h2>
      <% end %>
    </div>

    <div id="boxC">
      <% if @items.first.present? %>
        <table>
          <tbody>
            <thead>
              <tr id=texit_white>
              <th><nobr>商品画像</nobr></th>
              <th align="center">商品名</th>
              <th>価格</th>
              </tr>
            </thead>
            <% @items.each do |item| %>
              <tr>
                <td><%= image_tag item["smallImageUrls"][0] %></td>
                <td id=item_link><%= link_to truncate(item.name, length: 50 ), "#{item.url}" %></td>
                <td id=texit_white align="right"><%= number_with_delimiter(item.price) %>円</td>
                <% if logged_in? %>
                  <% if favorited? item.code %>
                    <td><%= link_to favorites_path(rakutenitem_id: item.code, item_name: item.name, item_url: item.url, itemimage_url: item["smallImageUrls"][0], keyword: @keyword), method: :delete do %>
                    <%= image_tag 'icons/heart-red.png', class: 'topic-index-icon' %></td>
                    <% end %>
                  <% else %>
                    <td><%= link_to favorites_path(rakutenitem_id: item.code, item_name: item.name, item_url: item.url, itemimage_url: item["smallImageUrls"][0], keyword: @keyword), method: :post do %>
                    <%= image_tag 'icons/heart.png', class: 'topic-index-icon' %></td>
                    <% end %>
                  <% end %>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <h2　class="texit_white">検索結果がありません</h2>
      <% end %>
    </div>
  </div>
  <div id="footer">
    <br>
    <br>
    <p id=texit_white align="center">Copyright © <%= Date.today.year %> Urge Inc. All rights reserved.</p>
  </div>
</div>

app/views/tweets/_tweet_list.html.erb
<% if @tweets1.present? %>
  <h2>トレンド</h2>
  <ul>
    <% @tweets1.each_with_index do |tweet1, i| %>
    <div class="list">
      <li> <%= tweet1.name %> </li>
    </div>
    <% end %>
  </ul>
<% end %>

app/views/tweets/search.html.erb
<div class='content'>
  <div id="search-box">
    <%= form_tag('/tweets/search', method: :get) do %>
      <%= text_field_tag :tweet, nil,  id: "tweet_search", name: "keyword", placeholder: "キーワードを打ち込んでください", style: "width: 200px;"%>
      <button title="検索" type="submit">検索</button>
    <% end %>
  </div>

  <div id='tweet_list'>
    <%= render partial: 'tweet_list' %>
  </div>
</div>